version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    volumes:
      - /etc/letsencrypt/live/kararizzardi.com:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    restart: always
