version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
